buildscript {
    repositories {
        maven { url = 'https://maven.minecraftforge.net' }
        mavenCentral()
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'maven-publish'

group = 'dev.rinchan'
version = '0.2.0+1.12.2'
archivesBaseName = 'rinlib-forge'
sourceCompatibility = targetCompatibility = '1.8'

minecraft {
    version = '1.12.2-14.23.5.2847'
    runDir = 'run'
    mappings = 'snapshot_20171003'
}

processResources {
    inputs.property 'version', project.version
    filesMatching('mcmod.info') {
        expand version: project.version
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
            artifactId = 'rinlib-forge'
        }
    }
}
