org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=1.20.4
minecraft_version_range=[1.20.4,1.21)
java_version=17

fabric_loader_version=0.15.11
fabric_api_version=0.97.3+1.20.4
forge_version=47.4.20
forge_version_range=[47,)
neo_version=20.4.251
neo_version_range=[20.4,)
loader_version_range=[4,)

mod_id=rinlib
mod_name=RinLib
mod_license=GPL-3.0-or-later
mod_version=0.2.0+1.20.4
mod_group_id=dev.rinchan
mod_authors=RinChan
mod_description=Shared runtime library for RinChan Minecraft mods.
