org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=22w24a
minecraft_version_range=[22w24a,22w24a]
java_version=17

fabric_loader_version=0.15.11
fabric_api_version=0.58.0+1.19
forge_version=41.0.62
forge_version_range=[41,)
neo_version=47.1.106
neo_version_range=[47.1,)
loader_version_range=[4,)

mod_id=rinlib
mod_name=RinLib
mod_license=GPL-3.0-or-later
mod_version=0.2.0+22w24a
mod_group_id=dev.rinchan
mod_authors=RinChan
mod_description=Shared runtime library for RinChan Minecraft mods.
